pipeline {
    agent any

    options {
        skipStagesAfterUnstable(false)
    }

    stages {

        stage('Build & Test') {
            stages {

                stage('Build') {
                    steps {
                      echo 'Building...'
                         sh 'exit 1'   // force failure
                         }
                    }

                stage('Test') {
                    steps {
                        echo 'Testing...'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed'
        }
    }
}
