pipeline {
    agent any

    stages {
        stage('Clone Check') {
            steps {
                echo 'Repository cloned successfully!'
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Install Frontend Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }
    }
}
